version: '3'

services:

  api:
    build: './src/api'
    volumes:
      - './data:/data'
    ports:
      - '8080:80'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8000:80'
