version: '3'

services:

  www2:
    restart: always
    build: './api2/www'
    volumes:
      - './api2/www/html:/usr/share/nginx/html'
    ports:
      - '8000:80'

  ws2:
    restart: always
    build: './api2/ws'
    volumes:
      - './api2/ws:/app'
      - './data:/data'
    ports:
      - '8080:80'
