version: '3'

services:
  desktop:
    build: './src/desktop'
    volumes:
      - './src/desktop:/app'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8000:80'

  ws:
    build: './src/ws'
    volumes:
      - './src/ws:/app'
    ports:
      - '8080:80'
