name: Github releases

on:
  workflow_dispatch:

jobs:
  github-releases:
    name: Github releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0

      - name: Install Python Flet
        run: python3 -m pip install flet pyinstaller pillow

      - name: Flet pack
        run: flet pack main.py

      - name: List files
        run: ls -laR

      # - name: Setup Python
      #   uses: actions/setup-python@v5.0.0
