name: Github releases

on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - Ubuntu
          - macOS

jobs:
  github-releases:
    name: Github releases
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0

      - name: Install Python Flet
        run: python3 -m pip install flet pyinstaller pillow

      - name: Flet pack
        run: flet pack ./src/desktop/main.py

      - name: List files
        run: ls -laR ./src/desktop
