name: Github releases

on:
  workflow_dispatch:

jobs:
  github-releases:
    name: Github releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
